name: "Intergration Plan workflow"

'on':
  push:
    branches:
      - test123
  pull_request:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_ACTION_WORKING_DIR: 'terraform'
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  integration:
    name: "Integration_lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Code"
        uses: "actions/checkout@v2"
        # with:
        # ref: ${{ github.event.pull_request.head.sha }} # Checkout PR HEAD commit instead of merge commit
      - name: Linting check
        id: fmt
        run: |
          cd ${GITHUB_WORKSPACE}
          bin/lint.sh integration
  integration:_plan:
    needs: integration_lint
    name: Integration_plan
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        # ref: ${{ github.event.pull_request.head.sha }}
      - name: Terraform plan
        id: plan
        run: |
         cd ${GITHUB_WORKSPACE}
         bin/plan.sh integration
      - name: Upload plan file
        uses: actions/upload-artifact@v2
        # with:
        # path: terraform/terraform-*.plan

      - name: Sync S3
        uses: adnanterraform/s3-sync-action@main
        env:
        # SOURCE_DIR: './src'
          AWS_REGION: 'eu-west-1'
          AWS_S3_BUCKET: 'adnan-terraform-project-github-actions-state'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
